apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  label:
    name: redis-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      port:
      - containerPort: 6379