apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 1
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: throw-dice
          restartPolicy: OnFailure
      backoffLimit: 25

