apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: my-busybox
  namespace: dev2406
spec:
  nodeName: master
  containers:
  - command: [ "sleep", "3600" ]
    image: busybox
    name: secret
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true

  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
      
