apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    name: gop-file-server
  ports:
    - nodePort: 31200
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    name: gop-fileserver
spec:
  containers:
    - image: kodekloud/fileserver
      name: gop-fileserver
      volumeMounts:
        - mountPath: "/web"
          name: data-store
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
