apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drupal
      app: drupal
  template:
    metadata:
      name: drupal
      labels:
        name: drupal
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal:8.6
          volumeMounts:
            - mountPath: "/var/www/html/modules"
              name: drupal-pvc
              subPath: "modules"
            - mountPath: "/var/www/html/profiles"
              name: drupal-pvc
              subPath: "profiles"
            - mountPath: "/var/www/html/sites"
              name: drupal-pvc
              subPath: "sites"
            - mountPath: "/var/www/html/themes"
              name:  drupal-pvc
              subPath: "themes"

      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
          command: [ "/bin/bash", "-c" ]
          volumeMounts:
            - mountPath: "/data"
              name: drupal-pvc

      volumes:
        - name: drupal-pvc
          persistentVolumeClaim:
            claimName: drupal-pvc
