apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    name: wordpress
  type: NodePort
  ports:
    - port: 80
      nodePort: 31004
      targetport: 80
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - port: 80
      targetport: 3306

